fix: notification test

diff --git a/.github/workflows/build_release_windows.yml b/.github/workflows/build_release_windows.yml
--- a/.github/workflows/build_release_windows.yml
+++ b/.github/workflows/build_release_windows.yml
@@ -241,9 +241,19 @@ jobs:
         run: |
           RELEASELOG=$(sh ./.github/scripts/udecode.sh ./RELEASELOG.md)
           RELEASELOG=${RELEASELOG//\\/\\\\}
-          RLT=$(curl --location --request POST 'https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage' -s --form-string chat_id=${{ env.chat-id }} --form 'text="$RELEASELOG"' --form 'parse_mode="Markdown"' --form 'disable_web_page_preview="true"' --form 'allow_sending_without_reply="true"' --form 'reply_markup="{\"inline_keyboard\":[[{\"text\":\"Download\",\"url\":\"https://github.com/JyCyunMe/Clash.Mini/releases/tag/v0.1.3.15-pre\"},{\"text\":\"GitHub\",\"url\":\"https://github.com/JyCyunMe/Clash.Mini\"}]]}"')
+          RLT=$(curl --location --request POST https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendMessage -s --form-string chat_id=${{ env.chat-id }} --form-string text="$RELEASELOG" --form-string parse_mode="Markdown" --form-string 'disable_web_page_preview="true"' --form-string allow_sending_without_reply="true" --form-string reply_markup="{\"inline_keyboard\":[[{\"text\":\"Download\",\"url\":\"https://github.com/JyCyunMe/Clash.Mini/releases/tag/${{ env.GIT_TAG }}\"},{\"text\":\"GitHub\",\"url\":\"https://github.com/JyCyunMe/Clash.Mini\"}]]}"
           echo $RLT
           IS_OK=`echo $RLT | jq ".ok"`
+          if [[ -e $IS_OK ]]; then
+            MSG_ID=`echo $RLT | jq ".result.message_id"`
+            DT_STR=`date "+%Y%m%d%H%M%S"`
+            PART_X64=`echo "${DT_STR}_Clash.Mini_X64" | base64 | tr -s "=" 2`
+            PART_X86=`echo "${DT_STR}_Clash.Mini_X86" | base64 | tr -s "=" 2`
+          else
+            echo "push to channel failed. Response: "
+            echo $RLT | jq .
+            exit 1
+          fi
 
 #      # 缓存Build文件
 #      - name: Cache node modules
