test: [ci config test] verify tag

diff --git a/.github/workflows/github_build_release.yml b/.github/workflows/github_build_release.yml
--- a/.github/workflows/github_build_release.yml
+++ b/.github/workflows/github_build_release.yml
@@ -237,14 +237,14 @@ jobs:
       # 验证提交
       - name: Verify Commit ⌨
         if: success()
-        shell: pwsh
+        shell: bash
         run: |
           curl 'https://github.com/jycyunme.gpg' | gpg --import
-          if (!(git verify-tag ${env:GIT_TAG})) {
-            echo "Tag ""${env:GIT_TAG}"" verify failed"
-            exit 1
-          }
-          echo "Tag ""${env:GIT_TAG}"" has been verified"
+
+          git verify-tag $GIT_TAG --raw 2>actual &&
+          grep "GOODSIG" actual &&
+          !grep "BADSIG" actual &&
+          echo "Tag \"$GIT_TAG\" has been verified" || echo "Tag \"$GIT_TAG\" verify failed" & exit 1
 
       # 发布到Releases
       - name: Publish to Releases 💸
