test: [ci config test] verify tag

diff --git a/.github/workflows/github_build_release.yml b/.github/workflows/github_build_release.yml
--- a/.github/workflows/github_build_release.yml
+++ b/.github/workflows/github_build_release.yml
@@ -242,9 +242,8 @@ jobs:
           curl 'https://github.com/jycyunme.gpg' | gpg --import
 
           git verify-tag $GIT_TAG --raw 2>actual &&
-          grep "GOODSIG" actual &&
-          ! grep "BADSIG" actual &&
-          echo "Tag \"$GIT_TAG\" has been verified" || echo "Tag \"$GIT_TAG\" verify failed" & exit 1
+          grep "GOODSIG" actual && ! grep "BADSIG" actual &&
+          echo "Tag \"$GIT_TAG\" has been verified" || (echo "Tag \"$GIT_TAG\" verify failed" & exit 1)
 
       # 发布到Releases
       - name: Publish to Releases 💸
