test: [ci config test] verify tag

diff --git a/.github/workflows/github_build_release.yml b/.github/workflows/github_build_release.yml
--- a/.github/workflows/github_build_release.yml
+++ b/.github/workflows/github_build_release.yml
@@ -240,7 +240,11 @@ jobs:
         shell: pwsh
         run: |
           curl 'https://github.com/jycyunme.gpg' | gpg --import
-          git verify-tag ${env:GIT_TAG} || exit 1
+          if (!(git verify-tag ${env:GIT_TAG})) {
+            echo "Tag ""${env:GIT_TAG}"" verify failed"
+            exit 1
+          }
+          echo "Tag ""${env:GIT_TAG}"" has been verified"
 
       # 发布到Releases
       - name: Publish to Releases 💸
